-- 20260601230000_outdoors_events_discovery_schedule.sql
--
-- ADR-016 PR 2: weekly cron for the Outdoors Events discovery Edge
-- Function. COMMENTED OUT by default — the founder uncomments + runs
-- this in the Supabase SQL editor after:
--   1. Deploying the function:
--        supabase functions deploy outdoors-events-discovery --no-verify-jwt
--   2. Setting the API key:
--        supabase secrets set ANTHROPIC_API_KEY=sk-ant-...
--   3. Storing the service-role key in Vault (same one the heartbeat +
--      briefing-pipeline crons use — if already stored, reuse it):
--        select vault.create_secret('<service-role-key>', 'antaeus_service_role_key', '');
--
-- Same pattern as the heartbeat + briefing-pipeline cron migrations.
-- pg_cron + pg_net must already be enabled (the heartbeat migration
-- enabled them).
--
-- Cadence: weekly, Monday 13:00 UTC (~7am Chicago winter / 8am summer).
-- Early enough that the operator opens Monday to a fresh list.

-- ─── Why alter database / current_setting doesn't work on Supabase ──
--
-- The SQL-editor `postgres` role lacks superuser, so
-- `alter database postgres set app.*` fails (SQLSTATE 42501). We read
-- the bearer token from Vault at fire time instead. The function URL
-- is hardcoded (not a secret — the function is publicly invokable;
-- authorization is what protects writes, via the service role).
--
-- Rotation: vault.update_secret(<uuid>, '<new-key>') — Vault is read
-- on every fire, so no re-scheduling needed.

-- select cron.schedule(
--     'antaeus-outdoors-events-discovery',
--     '0 13 * * 1',  -- Monday 13:00 UTC
--     $$
--     select net.http_post(
--         url := 'https://wjdqmgxwulqxxxnyuzyl.supabase.co/functions/v1/outdoors-events-discovery',
--         headers := jsonb_build_object(
--             'content-type', 'application/json',
--             'authorization', 'Bearer ' || (
--                 select decrypted_secret from vault.decrypted_secrets
--                 where name = 'antaeus_service_role_key'
--             )
--         ),
--         body := jsonb_build_object('action', 'run_all')
--     );
--     $$
-- );

-- Verify after scheduling:
--   select * from cron.job where jobname = 'antaeus-outdoors-events-discovery';
--
-- Manual one-off trigger (test before relying on the cron):
--   select net.http_post(
--       url := 'https://wjdqmgxwulqxxxnyuzyl.supabase.co/functions/v1/outdoors-events-discovery',
--       headers := jsonb_build_object(
--           'content-type', 'application/json',
--           'authorization', 'Bearer ' || (
--               select decrypted_secret from vault.decrypted_secrets
--               where name = 'antaeus_service_role_key'
--           )
--       ),
--       body := jsonb_build_object('action', 'run_all')
--   );
--   -- then inspect the response:
--   select * from net._http_response order by created desc limit 1;

-- Unschedule (if needed):
--   select cron.unschedule('antaeus-outdoors-events-discovery');
