#!/usr/bin/env python3
"""Generate per-glyph Preact components from the iconography mockup.

Reads deliverables/mockups/iconography-2026-06-07.html (spec 09's
visual source of truth), extracts each inventory cell's SVG, and emits
one .tsx per glyph under src/icons/glyphs/ plus manifest.ts.

THE MOCKUP IS THE MASTER. A production redraw lands in the mockup
first, then this script regenerates the components — never the other
way around. Hand-edits to generated files are lost on the next run by
design; one source of truth, propagated.

Glyphs are pure SVG; accent paths reference
var(--ds-icon-accent, currentColor) — the Icon wrapper sets the
variable from the manifest default; the currentColor fallback means a
glyph imported directly (without the wrapper) degrades to all-navy
instead of black-filled or invisible ticks.
"""
import re, pathlib, html

ROOT = pathlib.Path(__file__).resolve().parents[2]
MOCKUP = ROOT / "deliverables/mockups/iconography-2026-06-07.html"
OUT = ROOT / "src/icons/glyphs"
src = MOCKUP.read_text()

SPECIAL = {
    "ICP": ("icp", "Icp"), "Ctrl+K": ("ctrl-k", "CtrlK"),
    "the gauge": ("gauge", "Gauge"), "write up": ("write-up", "WriteUp"),
    "at risk": ("at-risk", "AtRisk"), "still weak": ("still-weak", "StillWeak"),
}
def norm(name):
    if name in SPECIAL: return SPECIAL[name]
    kebab = name.lower().replace(" ", "-")
    pascal = "".join(w.capitalize() for w in re.split(r"[\s-]+", name))
    return kebab, pascal

ACCENT = {"tk-o": "orange", "tk-b": "blue", "tk-g": "green",
          "tk-a": "amber", "tk-r": "red", "fl-b": "blue"}

TEMPLATE = '''/**
 * @PASCAL@ — "@NAME@" glyph. GENERATED — do not hand-edit; the
 * iconography mockup is the master and the generator propagates it
 * (tools/design-system/generate-icons.py). Spec 09 construction:
 * 24px grid, 2px keyline, flat terminals, miter joins. Placeholder
 * quality until the production redraw lands in the mockup.
 */
import type { GlyphProps } from "../glyph";

export function @PASCAL@Glyph({ size }: GlyphProps) {
    return (
        <svg
            viewBox="0 0 24 24"
            width={size}
            height={size}
            aria-hidden="true"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="butt"
            stroke-linejoin="miter"
        >
            @BODY@
        </svg>
    );
}
'''

cells = re.findall(
    r'<div class="cell"><span class="ic"><svg viewBox="0 0 24 24">(.*?)</svg></span><span class="nm">(.*?)</span></div>',
    src, re.S)
assert len(cells) == 46, f"expected 46 inventory cells, got {len(cells)}"

entries = []
for inner, raw_name in cells:
    name = html.unescape(raw_name.strip())
    kebab, pascal = norm(name)
    found_accent = []
    def sub_el(m):
        tag, attrs = m.group(1), m.group(2)
        cls = re.search(r'class="(tk-[a-z]|fl-b)"', attrs)
        out = re.sub(r'\s*class="[^"]*"', "", attrs)
        out = re.sub(r'\s*style="stroke-width:3;?"', ' stroke-width="3"', out)
        if cls:
            c = cls.group(1)
            found_accent.append(ACCENT[c])
            if c == "fl-b":
                out += ' fill="var(--ds-icon-accent, currentColor)" stroke="none"'
            else:
                out += ' stroke="var(--ds-icon-accent, currentColor)"'
        return f"<{tag}{out}/>"
    body = re.sub(r"<(path|circle|rect)([^/]*?)/>", sub_el, inner.strip())
    body = "\n            ".join(l.strip() for l in body.splitlines() if l.strip())
    comp = (TEMPLATE.replace("@PASCAL@", pascal)
                    .replace("@NAME@", name)
                    .replace("@BODY@", body))
    (OUT / f"{pascal}.tsx").write_text(comp)
    entries.append((kebab, pascal, found_accent[0] if found_accent else None))

imports = "\n".join(f'import {{ {p}Glyph }} from "./glyphs/{p}";' for _, p, _a in entries)
names = ",\n    ".join(f'"{k}"' for k, _p, _a in entries)
rows = "\n".join(f'    "{k}": {p}Glyph,' for k, p, _a in entries)
accents = "\n".join(f'    "{k}": "{a}",' for k, _p, a in entries if a)
(ROOT / "src/icons/manifest.ts").write_text(f'''/**
 * Icon manifest — generated by tools/design-system/generate-icons.py
 * from the iconography mockup (spec 09 §3): 11 sacred nouns ·
 * 17 operator verbs · 11 system & wayfinding · 7 status = 46 glyphs.
 * DEFAULT_ACCENTS carries each glyph's rationed tick (09 §1.2);
 * glyphs absent from it are all-navy. Regenerate after a glyph
 * redraw; do not hand-edit.
 *
 * Bundling note: this registry imports all 46 glyphs, so <Icon>
 * carries the full set (~trivial at 46 small components on a desktop
 * product). Direct per-glyph imports stay tree-shakeable for the rare
 * consumer that wants one glyph without the registry.
 */
import type {{ FunctionComponent }} from "preact";
import type {{ GlyphProps }} from "./glyph";
import type {{ IconAccent }} from "./glyph";
{imports}

export const ICON_NAMES = [
    {names},
] as const;

export type IconName = (typeof ICON_NAMES)[number];

export const GLYPHS: Readonly<Record<IconName, FunctionComponent<GlyphProps>>> = {{
{rows}
}};

export const DEFAULT_ACCENTS: Readonly<Partial<Record<IconName, IconAccent>>> = {{
{accents}
}};
''')
print(f"generated {len(entries)} glyphs; accented: {sum(1 for e in entries if e[2])}")
